# Define reusable configurations using anchors
x-app: &default-app
  build:
    context: "."
  volumes:
    - .:/code
  restart: "unless-stopped"

services:
  db:
    image: postgres:latest  
    container_name: maple-db
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: maple_db_dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  web:
    <<: *default-app  # Reuse the default-app configuration
    container_name: maple-web
    command: >
      sh -c "wait-for-it.sh db:5432 
      -- python manage.py collectstatic --noinput 
      && python manage.py makemigrations 
      && python manage.py migrate 
      && gunicorn md_app.wsgi:application --bind 0.0.0.0:1091 --workers 4 --timeout 1200"
    volumes:
      - .:/code  # Override or add specific volumes if needed
    ports:
      - "1091:1091"
    depends_on:
      - db

  tailwind:
    <<: *default-app  # Reuse the default-app configuration
    container_name: maple-tailwind
    command: "python manage.py tailwind start"
    volumes:
      - .:/code  # Ensure volumes are consistent or override if necessary
    ports:
      - "3000:3000"  # Example port, adjust as needed
    tty: true
    depends_on:
      - web

  pgadmin:
    image: dpage/pgadmin4
    container_name: maple-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: myemail@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "2000:80"
    depends_on:
      - db
    volumes:
      - pg_admin:/var/lib/pgadmin

volumes:
  pg_data:
  pg_admin: