

services:
  db:
    image: postgres:latest  
    container_name: maple-db
    # restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
      # - ./create_user.sh:/docker-entrypoint-initdb.d/create_user.sh
    env_file:
      - .env
    environment:
      POSTGRES_DB: maple_db_dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

  web:
    build: .
    container_name: maple-web
    develop:
      watch: 
        - action: sync
          path: ./code
          target: /code
        - ignore:
            - node_modules/
    command: >
      sh -c "wait-for-it.sh db:5432 
      && python manage.py makemigrations 
      && python manage.py migrate 
      && python manage.py runserver 0.0.0.0:1091
      "
    volumes:
      - .:/code
      # - static_volume:/code/staticfiles
    ports:
      - "1091:1091"
    depends_on:
      - db

  # nginx:
  #   image: nginx:latest
  #   container_name: maple-nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Mounts custom nginx.conf
  #     - ./core/templates/core/404.html:/code/core/templates/core/404.html:ro  # Mounts custom 404.html
  #     - ./staticfiles:/code/staticfiles:ro  # Mounts static files
  #   ports:
  #   - "8991:8991"  
  #   depends_on:
  #     - web

  pgadmin:
    image: dpage/pgadmin4
    container_name: maple-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: myemail@example.com
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "2000:80"
    depends_on:
      - db
    volumes:
      - pg_admin:/var/lib/pgadmin

volumes:
  pg_data:
  pg_admin:
  # static_volume:


