# Generated by Django 5.1 on 2024-08-19 17:59

import core.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('report_timestamp', models.DateTimeField(auto_now=True)),
                ('property_address', models.CharField(max_length=455)),
                ('external_picture', models.ImageField(blank=True, null=True, upload_to=core.models.report_property_photo_upload_path)),
                ('external_logger', models.CharField(max_length=7)),
                ('company', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='companies/<company_id>/')),
                ('surveyor', models.CharField(max_length=255)),
                ('notes', models.TextField()),
                ('occupied', models.BooleanField(default=False)),
                ('occupied_during_all_monitoring', models.BooleanField(default=False)),
                ('number_of_occupants', models.IntegerField(default=0)),
                ('room_name', models.CharField(max_length=255)),
                ('room_picture', models.ImageField(blank=True, null=True, upload_to=core.models.room_photo_upload_path)),
                ('room_ambient_logger', models.CharField(max_length=7)),
                ('room_surface_logger', models.CharField(max_length=7)),
                ('room_monitor_area', models.CharField(blank=True, max_length=255, null=True)),
                ('room_mould_visible', models.BooleanField(default=False)),
                ('report_file', models.FileField(upload_to='reports/<report_id>/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
