# Generated by Django 5.1.1 on 2024-10-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_report_report_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downloads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='downloads/')),
            ],
            options={
                'verbose_name_plural': 'downloads',
                'db_table': 'md_downloads',
            },
        ),
    ]
