# Generated by Django 5.1.1 on 2024-10-02 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloads',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
