# Generated by Django 5.1 on 2024-08-20 19:53

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='room_ambient_logger',
        ),
        migrations.RemoveField(
            model_name='report',
            name='room_monitor_area',
        ),
        migrations.RemoveField(
            model_name='report',
            name='room_mould_visible',
        ),
        migrations.RemoveField(
            model_name='report',
            name='room_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='room_picture',
        ),
        migrations.RemoveField(
            model_name='report',
            name='room_surface_logger',
        ),
        migrations.AlterField(
            model_name='report',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to=core.models.company_logo_upload_path),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=255)),
                ('room_picture', models.ImageField(blank=True, null=True, upload_to=core.models.room_photo_upload_path)),
                ('room_ambient_logger', models.CharField(max_length=7)),
                ('room_surface_logger', models.CharField(max_length=7)),
                ('room_monitor_area', models.CharField(blank=True, max_length=255, null=True)),
                ('room_mould_visible', models.BooleanField(default=False)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='core.report')),
            ],
        ),
    ]
