# Generated by Django 5.1.7 on 2025-03-14 14:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_downloads_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='company_logo',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=core.models.company_logo_upload_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='external_picture',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=core.models.report_property_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, max_length=455, null=True, upload_to='reports_save/'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_picture',
            field=models.ImageField(blank=True, max_length=455, null=True, upload_to=core.models.room_photo_upload_path),
        ),
    ]
