# Generated by Django 5.1.3 on 2024-11-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pricesetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesetting',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen')], default='GBP', max_length=3),
        ),
    ]
