# Generated by Django 5.1.3 on 2024-11-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pricesetting_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesetting',
            name='billing_type',
            field=models.CharField(choices=[('per_item', 'Per Item'), ('per_time', 'Per Time (N Days)'), ('credit_based', 'Credit-Based')], default='per_item', max_length=20),
        ),
        migrations.AddField(
            model_name='pricesetting',
            name='credit_type',
            field=models.CharField(blank=True, choices=[('purchased', 'Purchased'), ('promotional', 'Promotional')], help_text="Applicable only for 'credit-based' billing.", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pricesetting',
            name='interval_days',
            field=models.PositiveIntegerField(blank=True, help_text="Applicable only for 'per_time' billing.", null=True),
        ),
    ]
