# Generated by Django 5.1.3 on 2024-11-29 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pricesetting_billing_type_pricesetting_credit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen')], default='GBP', max_length=3),
        ),
    ]
