# Generated by Django 5.1.3 on 2024-11-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_payment_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('CREDITS', 'Credits')], default='GBP', max_length=7),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar'), ('JPY', 'Japanese Yen'), ('CREDITS', 'Credits')], default='GBP', max_length=7),
        ),
    ]
