# Generated by Django 5.1.4 on 2024-12-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_currency_alter_pricesetting_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generated', 'Generated'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='pending', max_length=20),
        ),
    ]
