# Generated by Django 5.1.4 on 2024-12-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='status',
        ),
    ]
