# Generated by Django 5.1.4 on 2024-12-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('generated', 'Generated'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=20, null=True),
        ),
    ]
