# Generated by Django 5.1.4 on 2024-12-17 14:17

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    PaymentModel = apps.get_model("core", "payment")
    for row in PaymentModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_payment_uuid'),
    ]



    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]