# Generated by Django 5.1.4 on 2024-12-17 14:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_populate_uuid_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
