# Generated by Django 5.1.4 on 2025-01-06 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_payment_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('generated', 'Generated'), ('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20, null=True),
        ),
    ]
