# Generated by Django 5.1.5 on 2025-01-23 15:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=core.models.report_upload_file),
        ),
    ]
